plugin:
    name: 'xitara.forms::lang.plugin.name'
    description: 'xitara.forms::lang.plugin.description'
    author: 'Bradie Tilley'
    icon: oc-icon-list-alt
    homepage: ''
navigation:
    bradie-forms:
        label: 'Custom Forms'
        url: xitara/forms/form
        icon: icon-list-alt
        order: 500
        permissions:
            - xitara.forms.forms
            - xitara.forms.submissions
        sideMenu:
            bradie-forms-forms:
                label: Forms
                url: xitara/forms/form
                icon: icon-sitemap
                permissions:
                    - xitara.forms.forms
            bradie-forms-submissions:
                label: Submissions
                url: xitara/forms/submission
                icon: icon-database
                permissions:
                    - xitara.forms.submissions
permissions:
    xitara.forms.forms:
        tab: 'xitara.forms::lang.plugin.name'
        label: 'xitara.forms::lang.permissions.forms'
    xitara.forms.submissions:
        tab: 'xitara.forms::lang.plugin.name'
        label: 'xitara.forms::lang.permissions.submissions'
