list: $/xitara/forms/models/submission/columns.yaml
modelClass: Xitara\Forms\Models\Submission
title: Submission
recordUrl: 'xitara/forms/submission/details/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
