name: Form
modelClass: Xitara\Forms\Models\Form
form: $/xitara/forms/models/form/fields.yaml
defaultRedirect: xitara/forms/form
create:
    title: 'Create New Form'
    redirect: 'xitara/forms/form/update/:id'
    redirectClose: xitara/forms/form
    flashSave: 'Your form has been successfully created'
update:
    title: 'Update Form'
    redirect: xitara/forms/form
    redirectClose: xitara/forms/form
    flashSave: 'Your form has been successfully updated'
    flashDelete: 'Your form has been successfully deleted'
preview: {  }
