title: Field
modelClass: Xitara\Forms\Models\Field
list: $/xitara/forms/models/field/columns.yaml
recordUrl: 'xitara/forms/field/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
