name: Field
modelClass: Xitara\Forms\Models\Field
form: $/xitara/forms/models/field/fields.yaml
defaultRedirect: xitara/forms/field
create:
    redirect: 'xitara/forms/field/update/:id'
    redirectClose: xitara/forms/field
update:
    redirect: xitara/forms/field
    redirectClose: xitara/forms/field
preview: {  }
